import 'package:flutter/material.dart';

class OurProjects extends StatelessWidget {
  const OurProjects({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Our Projects"),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              Text(
                "OUR EXISTING CLIENT IN TRIVELLORE DISTRICT\n\n",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontWeight: FontWeight.w600,
                  fontSize: 17,
                  decoration: TextDecoration.underline,
                  color: Colors.black,
                ),
              ),
              Text(
                '''
1. BHARATHIDASAN MATRICULATION SCHOOL
2. POONTHALIR PLAY SCHOOL.
3. BANK OF INDIA - TIRUVELLORE
4. VIJAYA BANK TRIVELLORE
5. INDIAN BANK - POONDI
6. INDIAN BANK - KADAMBATHUR
7. PUNJAB NATIONAL BANK
8. UCO BANK PERAMBAKKAM
9. BANK OF INDIA - POOVALAM
10. BHARATHI PRESS
11. CHANDRU STRORES
12. ALICE SUPER MARKET
13. NEW KANDASAMY STORES
14. MSM MALIGAI STORES
15. DAILY DHEENA SUPER MARKET
16. VEL MURUGAN TRADERS
17. DAILY NEEDS SUPER MARKET
18. SRI JAIN WOOD &amp; GLASS
19. SRI SELVA VINAYAGA PLYWOODS
20. BHARATH HARDWARES.
21. NETPRO COMPUTERS
22. CONCORDE MOTORS
23. VEERA MOTORS (MAHINDRA TWO WHEELERS)
24. TDK MODERN RICEMILL
25. KMT MODERN RICE MILL
26. HITECH DIAGNOSTIC CENTRE
27. SARAVANA MEDICALS
28. SHANTHI MEDICALS
29. SRI SAI MEDICALS – THIRUPACHUR
30. NATHANS DENTAL CARE
31. DR. DAYALAN HOSPITAL
32. DR.JOHN BABU
33. JP DENTAL HOSPITAL
34. PRABU MULTISPACILITY HOSPITAL
35. GK HOSPITAL
36. GHUMCO NT AUTO PARTS
37. DYMOS LEAR SRIPERAMBADUR
38. HYUNDAI SANTRO CITY
.39 PRECISION PIPES &amp; PROFILS POLIVAKKAM
40. CATTERPILLAR –TRIVELLORE
41. ANJANEYA INDUSTRIES KAKKLUR
42. SARADHA ELECTRO PLATES KAKKLUR
43. SR ENTERPRISES
44. INDIAN FURNITURE
45. IFC FRIED CHICKEN
46. VASANTHA BAVAN HOTEL
47. SAKTHI BAVAN HOTEL
48. THAMBU CHETTIYAR PETROL BUNK
49. VISWAKESANA SCHOOL
50. RANGA COMMERCIAL INSTITUTE.
51. SPM TEA STALL.
52. COLLECTOR OFFICE TRIVELLORE
53. MUNICAPLATY OFFICE TRIVELLORE
54. GOVT -HANDICAPPED DIVISION
55. GOVT-HEARING HAID DIVISION
56. AMWAY TRIVELLORE
57. SRI AYYAPA CAR FASHIONS
58. SRI SAKTHI LINING WORKS
59. SPHA SALOON.
60. KAMAL SALOON
61. ROCKY SALOON
62. SHOBA ELECTRICALS
63. SANTOSH BUILDERS
64. SENCE 3D ELEVATIOND
65. GOPI BUILDER
66. M.S.V. CONSTRUCTIONS &amp; REAL ESTATE
67. LOTUS AQUA FARM
68. GOLDENTEX POONAMALLEE
69. SYNDICATE FASHIONS
70. SYNDICATE WOMENS HOSTEL
71. MODERN MEDICALS &amp; HOSPITAL POONAMALLEE
72. GURUHASTHI THANGA MALIGAI
73. RAILWAY STATION TRIVELLORE, GUMIDIPOONDI, VELLORE, KATPADI,
CHENGALPATTU, SULURPET, DHINDHIVANAM
74. MRP AUTO RUB KAKKALUR
75. GOLOTEX FASHIONS
76 .ALLICE THIRUNINDRAVUR
77. NEW CLASSIC MENSWARE
78. AARA SILKS
79. BM GUEST HOUSE
80. 7 STAR DIGITAL.
81. RM. GURST HOUSE
82. MURUGAN HARDWARES
83. KRISHNA TALKIS
84. STAR HAIR STYLE
85. LAKSHMI TALKIS
86. SATHIYAM TEXTILES
87. D.R.B.C.C.C.H.H.S.SCHOOL TRIVELLORE
88. CALAVALA KANNAN MATRIC SCHOOL TRIVELLORE
89. ARIYA HOTEL
90. GOUDI CHURCH
91. ALPHA MATRIC SCHOOL REDHILLS
92. MEENAKCHI RAMAKRISHNAN KALYANA MANDAPAM PERAMBAKKAM
93. S.T.P MINI PARTY HALL TRIVELLORE
94. BUTTERFLY WEDDING CARDS
95. REPCO BANK TRIVELLORE
96. NATURALS BEAUTY PARLOUR TRIVELLORE
97. KAMARAJ MATRICULATION SCHOOL TRIVELLORE
98. SRI NEKATHEN SCHOOL
99. BILLROTH HOSPITAL
100. CAPTAIN GYM
101. RKB HOSPITAL
102. S2 LADIES GYM
103. FOOD HOUSE
104. MINAR BIRIYANI
105. SRI SAI SALOON
106. CSC COMPUTER SYSTEMS
107. MANTO ENGINEERING
108. BORG WARNER KAKKALUR
109. TGI PACKAGING
110. RICO AUTOMOBILE
111.WRITER COMPANY
112. TOLL INDIA PVT LTD
113.KP COMPLEX
114.MOHANAVEL DENTAL CLINIC
115. Dr. SURESH DENTAL CLINIC
116.TONY AND GUYS TIRUVALLUR
117. COLLECTRATE OFFICE
118 .RTO OFFICE
119.NORTH WAY SALOON
220.SPEED GYM
221.SHRIRAM HOUSING FINANCE
222. SAI TRADERS RICE WHOLESALE
223.USHI SUSIRA COMPANY
224. AKSHAR INDUSTRIES
225. ADHANI PORT KATTUPALLI
226.Dr. PRABUSHANKAR\n\n
''',
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.black,
                ),
              ),
              Text(
                "Note: MORE THAN 8000 SATISFIED CUSTOMER IN TRIVELLORE\n\n",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontWeight: FontWeight.w600,
                  fontSize: 17,
                  decoration: TextDecoration.underline,
                  color: Colors.black,
                ),
              ),
              Text(
                "“We handle our customer with care”",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontWeight: FontWeight.w700,
                  fontSize: 22,
                  fontStyle: FontStyle.italic,
                  color: Colors.black,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
